### ISSUE TITLE
请问如何在宝塔面板中部署？

### ISSUE THREAD

**Issue by wow8szh** [skyxingcheng/bing#1]
我创建了一个Node项目，但是启动不成功，所以想请教如何在宝塔面板中部署。

**Comment by im-zhou** [comment]
请提供详细报错或无法启动的信息

**Comment by wow8szh** [comment]
我的步骤是这样的：
1. 拉取源文件，在宝塔里建立Node项目，设置目录，项目自动会获取到启动项目supervisor node bin/www
2. 宝塔可以一键安装项目中的依赖
3. 建立数据库，并导入bing.sql
4. 修改配置文件，因为我是私有的服务器部署，这里可能有点问题：
- 我没有CDN加速，留空
- 监听端口我填了443
- SERT不知道是什么作用，就随便填了7个随机字符
- ROOT是我域名地址 https://xxx.xxx.com
- 我没有七牛环境，请问那部分是必须的吗？
- 邮件和微博环境，我没有需求，也跳过了
- 数据库环境是本地数据库，这部分没问题
- 分辨率那部分，不知道怎么改，就默认了

然后尝试启动项目，显示启动失败，我猜想是配置文件没有写对

**Comment by im-zhou** [comment]
必须提供七牛环境，否则请自行修改源码改为本地存储，并且所有图片都会走CDN URL ,一并修改即可,建议去搞一个七牛云存储(免费的),(另外不建议直接监听443，除非你已经配置好HTTPS)
